Coreção do controle responsável por remover um atividade
A operação para atualizar uma atividade estava sendo realizada no controle responsavel pela remoção da atividade do banco de dados porem a operação de remoção sozinha já atualizava o banco de dados. a atualização de uma atividade já excluída causava a seguinte exceção.

org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1] with root cause org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1